GLINER:
  MODEL_NAME: "urchade/gliner_mediumv2.1"
  LABELS: ["Industry","sector"]

NAICS:
  SAVE_PATH: "app/NAICS.json"

VECTORDB:
  DATABASE_PATH: "NAICS-DB"
  COLLECTION_NAME: "naics_collection"
  EMBEDDING_MODEL_TYPE: "openai" #can be either "sentence_transformer" or "openai" 
  EMBEDDING_MODEL_NAME: "text-embedding-3-small" #If sentence_transformer, See the list here https://docs.trychroma.com/guides/embeddings default: all-MiniLM-L6-v2